### ISSUE TITLE
Binding events?

### ISSUE THREAD

**Issue by pieterjandesmedt** [paradox41/ng-chartist.js#26]
I'm confused about how to bind events to tho chart. For example, how would you bind a mouseover event to a bar chart to display a tooltip with the value of the bar?

**Comment by pieterjandesmedt** [comment]
This works, thanks!

**Comment by shlomogoldstein** [comment]
I cannot get this to work, there is no event mouseover

**Comment by paradox41** [comment]
The only events supported are whatever Chartist [supports](https://gionkunz.github.io/chartist-js/api-documentation.html#chartistbase-function-on). 

The docs say:

> Check the examples for supported events.

So you are just gonna have to go digging
